# Workflow to be triggered on actions to the repo

name: flutter_ci

on:
  push:
    branches: [ CI-CD ]
  pull_request:
    branches: [ CI-CD ]
  #workflow_dispatch:

jobs:
  build:
    # This job would run on a linux virtual machine (ubuntu)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Setting up Java environment. This is for building the Android app
      #- uses: actions/setup-java@v2
      #  with:
      #    java-version: '12.x'

    # Setting up Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 'dev', 'alpha', 'beta', default to: 'stable'
    #      flutter-version: '2.5.3' # can also specify exact version
         
      - run: flutter --version         
    # Get flutter dependencies
      - run: flutter pub get    
    # Checking for any formatting issues
    #  - run: flutter format --set-exit-if-changed .
    # Statically analyze the Dart code for any errors
    #  - run: flutter analyze .   
    # Widget tests
    #  - run: flutter test
      - run: flutter test --no-sound-null-safety
    # Build apk
    #  - run: flutter build apk
    #  - run: flutter build appbundle
    # Build for the web  
      - run: flutter build web --no-sound-null-safety
