name: aws_ecs_release

on:
  release: 
    types: created
  workflow_dispatch:


env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: 
  ECS_SERVICE: 
  ECS_CLUSTER: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets. }}
        aws-secret-access-key: ${{ secrets. }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Docker build
      run: 